[package]
name = "sip-core"
version = "0.2.0"
edition = "2021"
license.workspace = true

[dependencies]
bytes = { workspace = true }
smol_str = { workspace = true }
serde = { workspace = true }
percent-encoding = "2.3"

[dev-dependencies]
proptest = "1"
