[package]
name = "sip-proxy"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
anyhow = { workspace = true }
sip-core = { path = "../sip-core" }
sip-transaction = { path = "../sip-transaction" }
bytes = { workspace = true }
